<?php
/**
 * Plugin Name: Erfan Student System
 * Description: سیستم ورود، ثبت‌نام و پنل دانش‌آموز برای دوره آموزشی عرفان با بخش کلاس آنلاین.
 * Version: 2.0.0
 * Author: Erfan
 * License: GPL-2.0-or-later
 */
if (!defined('ABSPATH')) exit;
final class Erfan_Student_System {
 public static function init(){
  add_shortcode('erfan_login',[__CLASS__,'login']); add_shortcode('erfan_register',[__CLASS__,'register']); add_shortcode('erfan_panel',[__CLASS__,'panel']);
  add_action('wp_enqueue_scripts',[__CLASS__,'assets']); add_action('template_redirect',[__CLASS__,'protect_panel']); add_action('init',[__CLASS__,'handle_forms']);
 }
 public static function assets(){
  wp_register_style('erfan-student-system',false,[],'2.0.0'); wp_enqueue_style('erfan-student-system');
  wp_add_inline_style('erfan-student-system','.erfan-auth,.erfan-panel{direction:rtl}.erfan-auth{max-width:520px;margin:50px auto;padding:20px}.erfan-auth-card{background:#fff;border:1px solid #e7eaf0;border-radius:24px;padding:35px;box-shadow:0 15px 45px rgba(20,30,60,.1)}.erfan-logo{text-align:center;font-size:42px}.erfan-auth h1{text-align:center}.muted{color:#697386}.erfan-auth label{display:block;font-weight:600;margin:16px 0 7px}.erfan-auth input:not([type=checkbox]){width:100%;box-sizing:border-box;border:1px solid #d9deea;border-radius:12px;padding:13px}.erfan-auth button{width:100%;margin-top:22px;border:0;border-radius:12px;padding:14px;font-weight:700;background:#111827;color:#fff}.check{display:flex!important;gap:8px;font-weight:400!important}.switch{text-align:center}.erfan-box{max-width:650px;margin:40px auto;padding:24px;border-radius:18px;background:#f7f9fc;direction:rtl}.erfan-panel{max-width:1100px;margin:40px auto;padding:20px}.erfan-panel-hero{display:flex;gap:20px;align-items:center;padding:30px;border-radius:24px;background:linear-gradient(135deg,#111827,#374151);color:#fff}.erfan-panel-hero>span{font-size:55px}.erfan-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:24px}.erfan-card{padding:24px;border:1px solid #e5e7eb;border-radius:20px;background:#fff}.erfan-card a{display:inline-block;margin-top:12px;padding:10px 16px;border-radius:10px;background:#111827;color:#fff;text-decoration:none}.logout{display:inline-block;margin-top:20px}.erfan-bbb-card{padding:24px;border:1px solid #dbeafe;border-radius:20px;background:linear-gradient(135deg,#eff6ff,#fff);box-shadow:0 8px 24px rgba(37,99,235,.08)}.erfan-bbb-card h3{margin:0 0 8px}.erfan-bbb-btn{display:inline-block!important;background:#2563eb!important;color:#fff!important;padding:11px 18px!important;border-radius:11px!important;font-weight:700}.erfan-bbb-ready{color:#15803d;font-weight:700}@media(max-width:800px){.erfan-grid{grid-template-columns:1fr}}');
 }
 private static function page_url($slug){$p=get_page_by_path($slug);return $p?get_permalink($p):home_url('/'.trim($slug,'/').'/');}
 public static function activate(){foreach(['erfan-login'=>['ورود دانش‌آموز','[erfan_login]'],'erfan-register'=>['ثبت‌نام دانش‌آموز','[erfan_register]'],'erfan-panel'=>['پنل دانش‌آموز','[erfan_panel]']] as $slug=>$d){if(!get_page_by_path($slug))wp_insert_post(['post_title'=>$d[0],'post_name'=>$slug,'post_content'=>$d[1],'post_status'=>'publish','post_type'=>'page']);}flush_rewrite_rules();}
 public static function protect_panel(){if(is_page('erfan-panel')&&!is_user_logged_in()){wp_safe_redirect(self::page_url('erfan-login'));exit;}}
 public static function handle_forms(){
  if($_SERVER['REQUEST_METHOD']!=='POST'||empty($_POST['erfan_action']))return;
  if(empty($_POST['erfan_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['erfan_nonce'])),'erfan_forms'))return;
  $a=sanitize_key(wp_unslash($_POST['erfan_action']));
  if($a==='login'){$u=wp_signon(['user_login'=>sanitize_text_field(wp_unslash($_POST['username']??'')),'user_password'=>(string)($_POST['password']??''),'remember'=>!empty($_POST['remember'])],is_ssl());if(!is_wp_error($u)){wp_safe_redirect(self::page_url('erfan-panel'));exit;}}
  if($a==='register'){$un=sanitize_user(wp_unslash($_POST['username']??''));$em=sanitize_email(wp_unslash($_POST['email']??''));$pw=(string)($_POST['password']??'');$cf=(string)($_POST['password_confirm']??'');if(!$un||!$em||!$pw||$pw!==$cf||username_exists($un)||email_exists($em))return;$id=wp_create_user($un,$pw,$em);if(!is_wp_error($id)){wp_update_user(['ID'=>$id,'role'=>'subscriber']);wp_set_auth_cookie($id,true);wp_safe_redirect(self::page_url('erfan-panel'));exit;}}
 }
 private static function bbb_join_url($u){
  // The BBB join URL is generated/stored by the site's server-side integration.
  // Do not put an API secret in this plugin or in browser JavaScript.
  $url=apply_filters('erfan_student_bbb_join_url','',$u);
  return is_string($url)?$url:'';
 }
 public static function login(){if(is_user_logged_in())return '<div class="erfan-box">شما وارد شده‌اید. <a href="'.esc_url(self::page_url('erfan-panel')).'">ورود به پنل</a></div>';ob_start();?><div class="erfan-auth"><div class="erfan-auth-card"><div class="erfan-logo">🎓</div><h1>دوره آموزشی عرفان</h1><p class="muted">ورود به حساب دانش‌آموز</p><form method="post"><input type="hidden" name="erfan_action" value="login"><input type="hidden" name="erfan_nonce" value="<?php echo esc_attr(wp_create_nonce('erfan_forms')); ?>"><label>ایمیل / نام کاربری</label><input name="username" autocomplete="username" required><label>رمز عبور</label><input type="password" name="password" autocomplete="current-password" required><label class="check"><input type="checkbox" name="remember" value="1"> مرا به خاطر بسپار</label><button type="submit">ورود به پنل من</button></form><p class="switch">حساب ندارید؟ <a href="<?php echo esc_url(self::page_url('erfan-register')); ?>">ثبت‌نام کنید</a></p></div></div><?php return ob_get_clean();}
 public static function register(){if(is_user_logged_in())return '<div class="erfan-box">شما وارد شده‌اید. <a href="'.esc_url(self::page_url('erfan-panel')).'">پنل من</a></div>';ob_start();?><div class="erfan-auth"><div class="erfan-auth-card"><div class="erfan-logo">✨</div><h1>ثبت‌نام دانش‌آموز</h1><p class="muted">حساب آموزشی خودت را بساز</p><form method="post"><input type="hidden" name="erfan_action" value="register"><input type="hidden" name="erfan_nonce" value="<?php echo esc_attr(wp_create_nonce('erfan_forms')); ?>"><label>نام کاربری</label><input name="username" required><label>ایمیل</label><input type="email" name="email" required><label>رمز عبور</label><input type="password" name="password" required><label>تکرار رمز عبور</label><input type="password" name="password_confirm" required><button type="submit">ساخت حساب</button></form><p class="switch">حساب دارید؟ <a href="<?php echo esc_url(self::page_url('erfan-login')); ?>">ورود</a></p></div></div><?php return ob_get_clean();}
 public static function panel(){if(!is_user_logged_in())return ''; $u=wp_get_current_user();$bbb=self::bbb_join_url($u);ob_start();?><div class="erfan-panel"><div class="erfan-panel-hero"><span>🎓</span><div><p class="muted">خوش آمدی</p><h1><?php echo esc_html($u->display_name?:$u->user_login); ?> 👋</h1><p>از اینجا دوره‌ها و کلاس‌های خودت را مدیریت کن.</p></div></div><div class="erfan-grid"><div class="erfan-card"><b>📚 دوره‌های من</b><p>فعلاً دوره‌ای اختصاص داده نشده است.</p></div><div class="erfan-card"><?php if($bbb): ?><div class="erfan-bbb-card"><h3>🎥 کلاس آنلاین</h3><p class="erfan-bbb-ready">🟢 کلاس آماده ورود است</p><a class="erfan-bbb-btn" href="<?php echo esc_url($bbb); ?>" target="_blank" rel="noopener noreferrer">🎥 ورود به کلاس</a></div><?php else: ?><b>🎥 کلاس آنلاین</b><p>پس از اختصاص کلاس، لینک ورود به BigBlueButton اینجا نمایش داده می‌شود.</p><?php endif; ?></div><div class="erfan-card"><b>🏆 مسابقات KidCode</b><p>چالش‌ها و مسابقات آینده اینجا قرار می‌گیرند.</p></div></div><p><a class="logout" href="<?php echo esc_url(wp_logout_url(home_url('/'))); ?>">خروج از حساب</a></p></div><?php return ob_get_clean();}
}
Erfan_Student_System::init(); register_activation_hook(__FILE__,['Erfan_Student_System','activate']);
